name: xmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [x64, x86]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '>=2.7.5 <3.0.0'

      - name: Build Debug
        run: |
          xmake f -p windows -a ${{ matrix.arch }} -m debug -y -vD
          xmake build -y -vD

      - name: Build Release
        run: |
          xmake f -p windows -a ${{ matrix.arch }} -m release -y -vD
          xmake build -y -vD

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webview-windows-${{ matrix.arch }}
          path: ./build/windows/${{ matrix.arch }}/
